Normative: Adding Intl.ListFormat specification.
tc39/ecma402 pull request #456
Opened 2020-06-12 21:34 UTC by zbraniecki

Fixes #33.

Based on https://github.com/tc39/proposal-intl-list-format which is ready for Stage 4.

2020-06-23 02:00 UTC, sffc commented
Can you add some housekeeping changes with this PR:

- Add Intl.ListFormat to [Appendix A](https://tc39.es/ecma402/#annex-implementation-dependent-behaviour)
- Add to [Section 4](https://tc39.es/ecma402/#sec-api-overview)

With the above, if any of your other recent proposals are also missing, go ahead and add them.  I think it's fine if you do that in this PR, but you could make another PR if you or @gibson042 prefers.

2020-06-23 02:09 UTC, zbraniecki commented
Added. IIRC we didn't add `Array.toLocaleString` to use `ListFormat` yet, so I didn't extend that.

2020-06-23 02:30 UTC, sffc commented
> Added. IIRC we didn't add `Array.toLocaleString` to use `ListFormat` yet, so I didn't extend that.

Right; that's #422 :)

2020-07-25 18:27 UTC, zbraniecki commented
We reached Stage 4 last week and this PR should be ready to be merged.

2020-09-10 22:41 UTC, zbraniecki commented
@leobalter @gibson042 - ping?

2021-01-05 00:50 UTC, leobalter requested changes
We have some nit picks I can eventually address from my side.

cc @gibson042

2021-01-05 00:50 UTC, leobalter commented on spec/overview.html
> +          Directly, by using the constructors Intl.Collator, Intl.NumberFormat, Intl.DateTimeFormat, Intl.ListFormat or Intl.PluralRules to construct an object, specifying a list of preferred languag
```suggestion
          Directly, by using the constructors Intl.Collator, Intl.NumberFormat, Intl.DateTimeFormat, Intl.ListFormat, or Intl.PluralRules to construct an object, specifying a list of preferred languages and options to configure the behaviour of the resulting object. The object then provides a main function (compare, select, or format), which can be called repeatedly. It also provides a resolvedOptions function, which the application can use to find out the exact configuration of the object.
```

nit

2021-01-05 00:50 UTC, leobalter commented on spec/listformat.html
> +          1. Let _O_ be ObjectCreate(%ObjectPrototype%).
```suggestion
          1. Let _O_ be ObjectCreate(%Object.prototype%).
```

Also, we need to update ObjectCreate in the whole spec text, as a follow up. It's now used as `OrdinaryObjectCreate`.

2021-01-05 00:50 UTC, leobalter commented on spec/listformat.html
> +      The Intl.ListFormat prototype object is itself an ordinary object. <dfn>%ListFormatPrototype%</dfn> is not an Intl.ListFormat instance and does not have an [[InitializedListFormat]] internal sl
```suggestion
      The Intl.ListFormat prototype object is itself an ordinary object. <dfn>%ListFormat.prototype%</dfn> is not an Intl.ListFormat instance and does not have an [[InitializedListFormat]] internal slot or any of the other internal slots of Intl.ListFormat instance objects.
```

2021-01-05 00:50 UTC, leobalter commented on spec/listformat.html
> +        1. Let _listFormat_ be ? OrdinaryCreateFromConstructor(NewTarget, *"%ListFormatPrototype%"*, &laquo; [[InitializedListFormat]], [[Locale]], [[Type]], [[Style]], [[Templates]] &raquo;).
```suggestion
        1. Let _listFormat_ be ? OrdinaryCreateFromConstructor(NewTarget, *"%ListFormat.prototype%"*, &laquo; [[InitializedListFormat]], [[Locale]], [[Type]], [[Style]], [[Templates]] &raquo;).
```

2021-01-05 00:50 UTC, leobalter commented on spec/listformat.html
> +        The value of `Intl.ListFormat.prototype` is %ListFormatPrototype%.
```suggestion
        The value of `Intl.ListFormat.prototype` is %ListFormat.prototype%.
```

2021-01-05 00:50 UTC, leobalter commented on spec/listformat.html
> +      Intl.ListFormat instances inherit properties from %ListFormatPrototype%.
```suggestion
      Intl.ListFormat instances inherit properties from %ListFormat.prototype%.
```

2021-01-05 00:50 UTC, leobalter commented on spec/listformat.html
> +      <h1>Intl.ListFormat.prototype.resolvedOptions ()</h1>
```suggestion
      <h1>Intl.ListFormat.prototype.resolvedOptions ( )</h1>
```

2021-01-05 00:50 UTC, leobalter commented on spec/listformat.html
> +        1. Let _options_ be ! ObjectCreate(%ObjectPrototype%).
```suggestion
        1. Let _options_ be ! ObjectCreate(%Object.prototype%).
```

2021-01-05 00:53 UTC, leobalter approved these changes

2021-01-05 00:54 UTC, leobalter commented
All of the changes were editorial, minor fixes, there is no need to round this back and forth.

2021-01-05 00:54 UTC, merged