Normative: Adding Intl.DisplayNames specification.
tc39/ecma402 pull request #502
Opened 2020-09-12 16:43 UTC by FrankYFTang

Fixes https://github.com/tc39/ecma402/issues/31.

Based on https://github.com/tc39/proposal-intl-displaynames which is ready for Stage 4.

2020-09-24 00:58 UTC, FrankYFTang commented
We need to address the issue @anba raised about  "Conformance" section in this PR
https://github.com/tc39/proposal-intl-displaynames/issues/78

2021-01-05 01:45 UTC, leobalter requested changes

2021-01-05 01:45 UTC, leobalter commented on spec/conventions.html
> +          <td>The `Intl.DisplayNames` constructor (<emu-xref href="#sec-intl-displaynames-constructor"></emu-xref>).</td>
```suggestion
          <td>%DisplayNames%</td>
          <td>`Intl.DisplayNames`</td>
          <td>The `Intl.DisplayNames` constructor (<emu-xref href="#sec-intl-displaynames-constructor"></emu-xref>).</td>
```

2021-01-05 01:45 UTC, leobalter commented on spec/displaynames.html
> +          1. If _code_ does not matches the `unicode_language_id` production, throw a *RangeError* exceptipon.
```suggestion
        1. If _type_ is *"language"*, then
          1. If _code_ does not match the `unicode_language_id` production, throw a *RangeError* exception.
```

Following patterns with 262, wrap string representations with star and double quotes, e.g. `*"string"*` instead the backtick quotes.

2021-01-05 01:45 UTC, leobalter commented on spec/displaynames.html
> +          1. If _code_ does not matches the `unicode_region_subtag` production, throw a *RangeError* exceptipon.
```suggestion
        1. If _type_ is *"region"*, then
          1. If _code_ does not match the `unicode_region_subtag` production, throw a *RangeError* exception.
```

2021-01-05 01:45 UTC, leobalter commented on spec/displaynames.html
> +          1. If _code_ does not matches the `unicode_script_subtag` production, throw a *RangeError* exceptipon.
```suggestion
        1. If _type_ is *"script"*, then
          1. If _code_ does not match the `unicode_script_subtag` production, throw a *RangeError* exception.
```

2021-01-05 01:45 UTC, leobalter commented on spec/displaynames.html
> +        1. If ! IsWellFormedCurrencyCode(_code_) is *false*, throw a *RangeError* exceptipon.
```suggestion
        1. Assert: _type_ is *"currency"*.
        1. If ! IsWellFormedCurrencyCode(_code_) is *false*, throw a *RangeError* exception.
```

2021-01-05 01:45 UTC, leobalter commented on spec/displaynames.html
> +      The DisplayNames constructor is a standard built-in property of the Intl object.</p>
```suggestion
    <p>
      The DisplayNames constructor is a standard built-in property of the Intl object.
    </p>
```

2021-01-05 01:45 UTC, leobalter commented on spec/displaynames.html
> +        1. Let _fallback_ be ? GetOption(_options_, `"fallback"`, `"string"`, &laquo; `"code"`, `"none"` &raquo;, `"code"`).
```suggestion
        1. Let _displayNames_ be ? OrdinaryCreateFromConstructor(NewTarget, *"%DisplayNames.prototype%"*, &laquo; [[InitializedDisplayNames]], [[Locale]], [[Style]], [[Type]], [[Fallback]], [[Fields]] &raquo;).
        1. Let _requestedLocales_ be ? CanonicalizeLocaleList(_locales_).
        1. Let _options_ be ? ToObject(_options_).
        1. Let _opt_ be a new Record.
        1. Let _localeData_ be %DisplayNames%.[[LocaleData]].
        1. Let _matcher_ be ? GetOption(_options_, *"localeMatcher"*, *"string"*, &laquo; *"lookup"*, *"best fit"* &raquo;, *"best fit"*).
        1. Set _opt_.[[localeMatcher]] to _matcher_.
        1. Let _r_ be ResolveLocale(%DisplayNames%.[[AvailableLocales]], _requestedLocales_, _opt_, %DisplayNames%.[[RelevantExtensionKeys]]).
        1. Let _style_ be ? GetOption(_options_, *"style"*, *"string"*, &laquo; *"narrow"*, *"short"*, *"long"* &raquo;, *"long"*).
        1. Set _displayNames_.[[Style]] to _style_.
        1. Let _type_ be ? GetOption(_options_, *"type"*, *"string"*, &laquo; *"language"*, *"region"*, *"script"*, *"currency"* &raquo;, *undefined*).
        1. If _type_ is *undefined*, throw a *TypeError* exception.
        1. Set _displayNames_.[[Type]] to _type_.
        1. Let _fallback_ be ? GetOption(_options_, *"fallback"*, *"string"*, &laquo; *"code"*, *"none"* &raquo;, *"code"*).
```

2021-01-05 01:45 UTC, leobalter commented on spec/displaynames.html
> +        The value of *Intl.DisplayNames.prototype* is *%DisplayNamesPrototype%*.
```suggestion
        The value of `Intl.DisplayNames.prototype` is *%DisplayNames.prototype%*.
```

2021-01-05 01:45 UTC, leobalter commented on spec/displaynames.html
> +      The Intl.DisplayNames prototype object, referred to as *%DisplayNamesPrototype%*, is itself an ordinary object. It is not a Intl.DisplayNames instance, does not have an [[InitializedDisplayName
```suggestion
      The Intl.DisplayNames prototype object is itself an ordinary object. <dfn>%DisplayNames.prototype%</dfn> is not an Intl.DisplayNames instance and does not have an [[InitializedDisplayNames]] internal slot or any of the other internal slots of Intl.DisplayNames instance objects.
```

2021-01-05 01:45 UTC, leobalter commented on spec/displaynames.html
> +        The initial value of the @@toStringTag property is the string value `"Intl.DisplayNames"`.
```suggestion
        The initial value of the @@toStringTag property is the string value *"Intl.DisplayNames"*.
```

2021-01-05 01:45 UTC, leobalter commented on spec/displaynames.html
> +        <li>The display name styles fields under display name type `"currency"` should contain Records, with keys corresponding to currency codes. The value of these fields must be string values.</li
```suggestion
        <li>[[LocaleData]].[[&lt;_locale_&gt;]] must have a [[types]] field for all locale values _locale_. The value of this field must be a Record, which must have fields with the names of one of the valid display name types: *"language"*, *"region"*, *"script"*, and *"currency"*.</li>
        <li>The value of fields *"language"*, *"region"*, *"script"*, and *"currency"* must be a Records which must have fields with the names of one of the valid display name styles: *"narrow"*, *"short"*, and *"long"*.</li>
        <li>The display name styles fields under display name type *"language"* should contain Records, with keys corresponding to language codes according to `unicode_language_id` production. The value of these fields must be string values.</li>
        <li>The display name styles fields under display name type *"region"* should contain Records, with keys corresponding to region codes. The value of these fields must be string values.</li>
        <li>The display name styles fields under display name type *"script"* should contain Records, with keys corresponding to script codes. The value of these fields must be string values.</li>
        <li>The display name styles fields under display name type *"currency"* should contain Records, with keys corresponding to currency codes. The value of these fields must be string values.</li>
```

2021-01-05 01:45 UTC, leobalter commented on spec/displaynames.html
> +        1. If _displayNames_.[[Fallback]] is `"code"`, return _code_.
```suggestion
        1. If _displayNames_.[[Fallback]] is *"code"*, return _code_.
```

2021-01-05 01:45 UTC, leobalter commented on spec/displaynames.html
> +            <td>`"fallback"`</td>
```suggestion
            <td>*"locale"*</td>
          </tr>
          <tr>
            <td>[[Style]]</td>
            <td>*"style"*</td>
          </tr>
          <tr>
            <td>[[Type]]</td>
            <td>*"type"*</td>
          </tr>
          <tr>
            <td>[[Fallback]]</td>
            <td>*"fallback"*</td>
```

2021-01-05 01:45 UTC, leobalter commented on spec/displaynames.html
> +      Intl.DisplayNames instances are ordinary objects that inherit properties from %DisplayNamesPrototype%.
```suggestion
      Intl.DisplayNames instances are ordinary objects that inherit properties from %DisplayNames.prototype%.
```

2021-01-05 01:45 UTC, leobalter commented on spec/displaynames.html
> +      <li>[[Fallback]] is one of the String values `"code"`, or `"none"`, identifying the fallback return when the system does not have the requested display name.</li>
```suggestion
      <li>[[Style]] is one of the String values *"narrow"*, *"short"*, or *"long"*, identifying the display name style used.</li>
      <li>[[Type]] is one of the String values *"language"*, *"region"*, *"script"*, or *"currency"*, identifying the type of the display names requested.</li>
      <li>[[Fallback]] is one of the String values *"code"*, or *"none"*, identifying the fallback return when the system does not have the requested display name.</li>
```

2021-01-05 01:45 UTC, leobalter commented on spec/displaynames.html
> +        must have fields with keys corresponding to codes according to [[Style]] and [[Type]].</li>
```suggestion
      <li>[[Fields]] is a Record (see <emu-xref href="#sec-Intl.DisplayNames-internal-slots"></emu-xref>) which must have fields with keys corresponding to codes according to [[Style]] and [[Type]].</li>
```

2021-01-05 01:49 UTC, leobalter commented
As my review got too verbose, I'd like to bring back a pending feedback from @anba:

> https://tc39.es/ecma402/#conformance lists options which are allowed to have implementation-defined behaviour. For Intl.DisplayNames, the "style" and "type" options should probably be listed there. I'm not yet sure if it makes sense to allow implementation-defined behaviour for the "fallback" option, because I don't exactly know what other kind of fallback should happen here.

@FrankYFTang I've got some minor suggestions, all editorial which I can apply (probably tomorrow). 

I can also help on the missing conformance part, please let me know!

2021-01-05 21:08 UTC, FrankYFTang commented
> @FrankYFTang I've got some minor suggestions, all editorial which I can apply (probably tomorrow).


Thanks. Great ! 

> 
> I can also help on the missing conformance part, please let me know!

That will be nice.

2021-01-05 21:09 UTC, leobalter approved these changes

2021-01-05 21:11 UTC, leobalter commented
Ok, the conflicts are resolved and I'll take a look at this conformance part. I believe it's best to do in a follow up PR we work through this week.

2021-01-05 21:19 UTC, FrankYFTang commented
> Ok, the conflicts are resolved and I'll take a look at this conformance part. I believe it's best to do in a follow up PR we work through this week.

Agree

2021-01-06 00:14 UTC, merged