Normative: Adding Intl.DateTimeFormat formatRange/formatRangeToParts specification
tc39/ecma402 pull request #532
Opened 2021-01-15 04:51 UTC by fabalbon

Fix #188

2021-02-01 08:54 UTC, ryzokuken requested changes
When rebasing Temporal on top of this proposal, we uncovered a few lint errors. Please fix them (and all others that come up from `ecmarkup`, Temporal only uses a subset of the spec).

2021-02-01 08:54 UTC, ryzokuken commented on spec/datetimeformat.html
> +        1. While _dateFieldsPracticallyEqual_ is *true* and _patternContainsLargerDateField_ is *false*, repeat for each row of <emu-xref href="#table-datetimeformat-rangepatternfields"></emu-xref> i
`expected freeform line with substeps to end with ":" (found " in order, except the header row")`

2021-02-01 08:54 UTC, ryzokuken commented on spec/datetimeformat.html
> +          1. For each _r_ in _result_ do
```suggestion
          1. For each _r_ in _result_, do
```

`expected "For each" with substeps to end with ", do" (found " do")`

2021-02-01 08:54 UTC, ryzokuken commented on spec/datetimeformat.html
> +          1. For each _r_ in _result_ do
`expected "for each" to have a type name or "element" before the loop variable`

2021-02-01 08:54 UTC, ryzokuken commented on spec/datetimeformat.html
> +        1. For each _rangePatternPart_ in _rangePattern_.[[PatternParts]], do
`expected "for each" to have a type name or "element" before the loop variable`

2021-02-01 08:54 UTC, ryzokuken commented on spec/datetimeformat.html
> +          1. For each _r_ in _partResult_, do
`expected "for each" to have a type name or "element" before the loop variable`

2021-02-01 08:54 UTC, ryzokuken commented on spec/datetimeformat.html
> +            1. Else if _f_ is *"narrow"*, *"short"*, or *"long"*, then let _fv_ be a String value representing _v_ in the form given by _f_; the String value depends upon the implementation and the e
```suggestion
            1. Else if _f_ is *"narrow"*, *"short"*, or *"long"*, then let _fv_ be a String value representing _v_ in the form given by _f_; the String value depends upon the implementation and the effective locale and calendar of _dateTimeFormat_. If _p_ is *"month"* and _rangeFormatOptions_ is *undefined*, then the String value may also depend on whether _dateTimeFormat_.[[Day]] is *undefined*. If _p_ is *"month"* and _rangeFormatOptions_ is not *undefined*, then the String value may also depend on whether _rangeFormatOptions_.[[day]] is *undefined*. If _p_ is *"timeZoneName"*, then the String value may also depend on the value of the [[InDST]] field of _tm_. If _p_ is *"era"* and _rangeFormatOptions_ is *undefined*, then the String value may also depend on whether _dateTimeFormat_.[[Era]] is *undefined*. If _p_ is *"era"* and _rangeFormatOptions_ is not *undefined*, then the String value may also depend on whether _rangeFormatOptions_.[[era]] is *undefined*. If the implementation does not have a localized representation of _f_, then use _f_ itself.
```

`multiple consecutive spaces are not allowed`

2021-02-15 14:15 UTC, Ms2ger commented on spec/datetimeformat.html
> +            1. Let _rp_ be _rangePatterns_.[[<_fieldName_>]].
```suggestion
            1. Let _rp_ be _rangePatterns_.[[&lt;_fieldName_&gt;]].
```

2021-02-15 14:15 UTC, Ms2ger commented on spec/datetimeformat.html
> +              1. Let _v2_ be _tm2_.[[<_fieldName_>]].
```suggestion
              1. Let _v1_ be _tm1_.[[&lt;_fieldName_&gt;]].
              1. Let _v2_ be _tm2_.[[&lt;_fieldName_&gt;]].
```

2021-02-16 10:10 UTC, ryzokuken approved these changes
LGTM with @Ms2ger's suggestions applied.

2021-02-18 01:18 UTC, leobalter approved these changes

2021-02-18 01:18 UTC, leobalter commented on spec/datetimeformat.html
> +          1. Add to _format_ all fields from _timeFormat_ except [[pattern]], [[rangePatterns]], [[pattern12]] and [[rangePatterns12]], if present.
```suggestion
          1. Add to _format_ all fields from _timeFormat_ except [[pattern]], [[rangePatterns]], [[pattern12]], and [[rangePatterns12]], if present.
```

2021-02-18 01:26 UTC, leobalter commented
LGTM

We have a few conflicts in the CI but I'm planning to address them after merging.

2021-02-18 01:26 UTC, merged