Editorial: clarify parameter type
tc39/ecma402 pull request #651
Opened 2022-01-24 21:11 UTC by jugglinmike

The term "numeric value" does not describe a type. Replace it with a
type inferred from the abstract operation's only call site.

2022-02-01 23:18 UTC, gibson042 requested changes
I don't think this holds up unless the scope is expanded to properly fix #648, because **many** related operations are incoherent in the same way:
* [FormatNumeric](https://tc39.es/ecma402/#sec-formatnumber) is documented to accept <var>x</var> (which must be a Number or BigInt value), but FormatDateTimePattern incorrectly invokes it with mathematical values.
* FormatNumeric then sends it to PartitionNumberPattern, which also expects <var>x</var> (a Number or a BigInt).
* PartitionNumberPattern handles finite <var>x</var> by sending it to ComputeExponent (which implicitly and incorrectly treats it as a mathematical value and returns a mathematical value) and FormatNumericToString, replacing <var>x</var> with the [[RoundedNumber]] slot of the record returned by FormatNumericToString.
  * FormatNumericToString accepts <var>x</var> (which must be a Number or BigInt value), but incorrectly performs some operations upon it that are only valid with mathematical values. It replaces <var>x</var> with a mathematical value from the [[RoundedNumber]] slot of a record returned by either ToRawPrecision or ToRawFixed, and then returns either that mathematical value or its negation in [[RoundedNumber]].
* Back in PartitionNumberPattern, <var>x</var> could be either the supposedly Number/BigInt input **or** a mathematical value from FormatNumericToString.
* PartitionNumberPattern sends <var>x</var> to GetNumberFormatPattern, which performs some operations upon it that are only valid for mathematical values and others that can only succeed if it is a Number.
* PartitionNumberPattern then sends the type-confused <var>x</var> to PartitionNotationSubPattern, the current object of this PR, which expects <var>x</var> (which is a numeric value after rounding is applied) and is sufficiently vague in its treatment that no further specification seems required.

2022-03-15 08:19 UTC, ryzokuken commented
@jugglinmike any updates on this?

2022-03-15 18:07 UTC, jugglinmike commented
Nope

2023-08-23 23:13 UTC, sffc commented
I'm going to close this; @jugglinmike  please make an issue with follow-up work.

2023-08-23 23:13 UTC, closed without merging