capitalized all [[LocaleRelated]] slots
tc39/ecma402 pull request #749
Opened 2023-01-25 16:49 UTC by ben-allen

2023-01-25 18:09 UTC, ljharb approved these changes

2023-01-26 21:50 UTC, gibson042 reviewed
Thank you! But unfortunately, widespread use of the [[[\<_name_>]]](https://tc39.es/ecma402/#conventions) indirection pattern to map option values directly to field names makes it much more complicated than a straightforward find and replace.

2023-01-26 21:50 UTC, gibson042 commented on spec/datetimeformat.html
>            Each of the records must also have the following fields:
```suggestion
          Each Date-Time Format Pattern Record must also have the following fields:
```

2023-01-26 21:50 UTC, gibson042 commented on spec/datetimeformat.html
>           </li>
These [[full]]/[[long]]/etc. fields also must be lowercase to correspond with the current definition of [DateTimeStyleFormat](https://tc39.es/ecma402/#sec-date-time-style-format).
```suggestion
        <li>
          [[LocaleData]].[[&lt;_locale_&gt;]] must have a [[Styles]] field. This [[Styles]] field must be a Record with [[&lt;_calendar_&gt;]] fields for all calendar values _calendar_. The value of each [[&lt;_calendar_&gt;]] field must be a Record with all of the following fields:
          <ul>
            <li>A [[DateFormat]] field whose value is a Record with [[full]], [[long]], [[medium]] and [[short]] fields, the value for each of which has the same structure and constraints as a Date-Time Format Pattern Record element of the [[LocaleData]].[[<_locale_>]].[[<_calendar_>]] List.</li>
            <li>A [[TimeFormat]] field whose value is a Record with [[full]], [[long]], [[medium]] and [[short]] fields, the value for each of which has the same structure and constraints as a Date-Time Format Pattern Record element of the [[LocaleData]].[[<_locale_>]].[[<_calendar_>]] List.</li>
            <li>A [[DateTimeFormat]] field whose value is a Record with [[full]], [[long]], [[medium]] and [[short]] fields, the value for each of which is a string containing substrings *"{0}"* and *"{1}"* (serving as respective placeholders for time and date patterns).</li>
            <li>A [[DateTimeRangeFormat]] field whose value is a Record with [[full]], [[long]], [[medium]] and [[short]] fields (corresponding with the respective DateTimeFormat [[DateStyle]] values), the value for each of which is a Record describing a collection of format patterns for that date style. That nested Record has [[full]], [[long]], [[medium]] and [[short]] fields (corresponding with the respective DateTimeFormat [[TimeStyle]] values), the value for each of which is a Record with [[RangePatterns]] and [[RangePatterns12]] fields whose values have the same structure and constraints as the respectively-named fields of a Date-Time Format Pattern Record.</li>
          </ul>
        </li>
```

2023-01-26 21:50 UTC, gibson042 commented on spec/datetimeformat.html
> +          <li>[[RangePatterns]]:</li>
```suggestion
          <li>[[hour]]: *"numeric"*</li>
          <li>[[minute]]: *"numeric"*</li>
          <li>[[Pattern]]: *"{hour}:{minute}"*</li>
          <li>[[Pattern12]]: *"{hour}:{minute} {ampm}"*</li>
          <li>[[RangePatterns]]:</li>
```

2023-01-26 21:50 UTC, gibson042 commented on spec/datetimeformat.html
> +              <li>[[Minute]]: *"numeric"*</li>
```suggestion
              <li>[[hour]]: *"numeric"*</li>
              <li>[[minute]]: *"numeric"*</li>
```

2023-01-26 21:50 UTC, gibson042 commented on spec/datetimeformat.html
> +              <li>[[Minute]]: *"numeric"*</li>
```suggestion
              <li>[[hour]]: *"numeric"*</li>
              <li>[[minute]]: *"numeric"*</li>
```

2023-01-26 21:50 UTC, gibson042 commented on spec/datetimeformat.html
> +              <li>[[Minute]]: *"numeric"*</li>
```suggestion
              <li>[[year]]: *"2-digit"*</li>
              <li>[[month]]: *"numeric"*</li>
              <li>[[day]]: *"numeric"*</li>
              <li>[[hour]]: *"numeric"*</li>
              <li>[[minute]]: *"numeric"*</li>
```

2023-01-26 21:50 UTC, gibson042 commented on spec/datetimeformat.html
> +              <li>[[Minute]]: *"numeric"*</li>
```suggestion
              <li>[[hour]]: *"numeric"*</li>
              <li>[[minute]]: *"numeric"*</li>
```

2023-01-26 21:50 UTC, gibson042 commented on spec/datetimeformat.html
> +              <li>[[Minute]]: *"numeric"*</li>
```suggestion
              <li>[[hour]]: *"numeric"*</li>
              <li>[[minute]]: *"numeric"*</li>
```

2023-01-26 21:50 UTC, gibson042 commented on spec/datetimeformat.html
> +              <li>[[Minute]]: *"numeric"*</li>
```suggestion
              <li>[[year]]: *"2-digit"*</li>
              <li>[[month]]: *"numeric"*</li>
              <li>[[day]]: *"numeric"*</li>
              <li>[[hour]]: *"numeric"*</li>
              <li>[[minute]]: *"numeric"*</li>
```

2023-01-26 21:50 UTC, gibson042 commented on spec/listformat.html
> +        <li>[[LocaleData]].[[&lt;_locale_&gt;]] is a Record which has three fields [[Conjunction]], [[Disjunction]], and [[Unit]]. Each of these is a Record which must have fields with the names of t
These also cannot change while the [Intl.ListFormat constructor](https://tc39.es/ecma402/#sec-Intl.ListFormat) uses lowercase option values as lookup keys.
```suggestion
        <li>[[LocaleData]].[[&lt;_locale_&gt;]] is a Record which has three fields [[conjunction]], [[disjunction]], and [[unit]]. Each of these is a Record which must have fields with the names of three formatting styles: [[long]], [[short]], and [[narrow]].</li>
```

2023-01-26 21:50 UTC, gibson042 commented on spec/numberformat.html
> +        <li>[[LocaleData]].[[&lt;_locale_&gt;]] must have a [[Patterns]] field for all locale values _locale_. The value of this field must be a Record, which must have fields with the names of the f
This change _can_ work, but it requires some finesse.
```suggestion
        <li>[[LocaleData]].[[&lt;_locale_&gt;]] must have a [[Patterns]] field for all locale values _locale_. The value of this field must be a Record, which must have fields corresponding with  the names of the four number format styles after uppercasing the initial letter: [[Decimal]], [[Percent]], [[Currency]], and [[Unit]].</li>
```

2023-01-26 21:50 UTC, gibson042 commented on spec/numberformat.html
>            The *"currency"* may have additional fields with keys corresponding to currency codes according to <emu-xref href="#sec-currency-codes"></emu-xref>.
```suggestion
          The two fields [[Currency]] and [[Unit]] noted above must be Records with at least one field, [[Fallback]].
          The [[Currency]] Record may have additional fields with keys corresponding to currency codes according to <emu-xref href="#sec-currency-codes"></emu-xref>.
```
and so on. Note also that the change from "fallback" to "Fallback" will require fixes in [GetNumberFormatPattern](https://tc39.es/ecma402/#sec-getnumberformatpattern).

2023-01-26 21:50 UTC, gibson042 commented on spec/numberformat.html
>            Additionally, the values within the *"percent"* field must also contain the substring *"{percentSign}"*; the values within the *"currency"* field must also contain one or more of the follow
```suggestion
          Additionally, the values within the [[Percent]] field must also contain the <emu-not-ref>substring</emu-not-ref> *"{percentSign}"*; the values within the [[Currency]] field must also contain one or more of the following substrings: *"{currencyCode}"*, *"{currencyPrefix}"*, or *"{currencySuffix}"*; and the values within the [[Unit]] field must also contain one or more of the following substrings: *"{unitPrefix}"* or *"{unitSuffix}"*.
```

2023-01-26 21:50 UTC, gibson042 commented on spec/numberformat.html
>            1. Let _patterns_ be _patterns_.[[&lt;_unit_&gt;]].
```suggestion
          1. If _patterns_ doesn't have a field [[&lt;_unit_&gt;]], then
            1. Let _patterns_ be _patterns_.[[Fallback]].
          1. Else,
            1. Let _patterns_ be _patterns_.[[&lt;_unit_&gt;]].
```

2023-01-26 21:50 UTC, gibson042 commented on spec/numberformat.html
>            1. Let _patterns_ be _patterns_.[[&lt;_currencySign_&gt;]].
```suggestion
          1. If _patterns_ doesn't have a field [[&lt;_currency_&gt;]], then
            1. Let _patterns_ be _patterns_.[[Fallback]].
          1. Else,
            1. Let _patterns_ be _patterns_.[[&lt;_currency_&gt;]].
          1. Let _patterns_ be _patterns_.[[&lt;_currencyDisplay_&gt;]].
          1. Let _patterns_ be _patterns_.[[&lt;_currencySign_&gt;]].
```

2023-01-26 21:51 UTC, gibson042 requested changes
As noted above, this needs tweaking.

2023-01-28 01:02 UTC, closed without merging