Editorial: added note indicating that we update to reflect UTS 35 on an ad-hoc b…
tc39/ecma402 pull request #779
Opened 2023-05-04 13:49 UTC by ben-allen

fix #584

2023-05-04 15:10 UTC, ljharb commented on spec/normative-references.html
> +    Sections of this specification that depend on UTS 35, CLDR and other Unicode standards are updated on a best-effort basis, but are not guaranteed to be up-to-date with those standards.
```suggestion
    Sections of this specification that depend on UTS 35, CLDR, and other Unicode standards are updated on a best-effort basis, but are not guaranteed to be up-to-date with those standards.
```

2023-05-04 17:18 UTC, FrankYFTang approved these changes
LGTM. I think this is good because that will give all TG2 members a chance to express concern if UTS35 / CLDR add items implementation have issue to implement in term of both the timing or technical difficult (if that happen).

2023-06-15 20:07 UTC, gibson042 requested changes
Thanks!

2023-06-16 20:25 UTC, ben-allen commented on spec/normative-references.html
> +    Sections of this specification that depend on UTS 35, CLDR, and other Unicode standards are updated on a best-effort basis, but are not guaranteed to be up-to-date with those standards.
good idea, since I'm guessing there's nothing related to any of the references that are updated on anything _but_ an ad hoc basis.

2023-06-17 06:14 UTC, gibson042 approved these changes

2023-06-17 06:15 UTC, merged