Editorial: Refactor Locale and Parameter Negotiation to better align with BCP 47
tc39/ecma402 pull request #871
Opened 2024-03-01 03:49 UTC by gibson042

Stacked on #870, and best reviewed commit-by-commit starting from the third commit.

[RFC 4647 section 2.3](https://www.rfc-editor.org/rfc/rfc4647.html#section-2.3) defines "language priority list" as "_a prioritized or weighted list of language ranges_", and corresponds to _requestedLocales_ in various ECMA-402 operations.
[RFC 4647 section 3](https://www.rfc-editor.org/rfc/rfc4647.html#section-3) differentiates "matching schemes" applying such lists against available locales into "filtering" (producing zero or more matches) and "lookup" (producing exactly one match).

This PR incorporates those terms and refactors the algorithms to better align with BCP 47, consolidating many of them and establishing clear entry points at ResolveLocale for lookup and FilterLocales (née SupportedLocales) and filtering.

2024-03-06 18:56 UTC, ben-allen requested changes
I love this -- much better documented than before. I've made some wording suggestions/tweaks, but otherwise I approve.

2024-03-06 18:56 UTC, ben-allen commented on spec/negotiation.html
> +        <dd>It performs "lookup" as defined in <a href="https://www.rfc-editor.org/rfc/bcp/bcp47.txt">BCP 47</a> at <a href="https://www.rfc-editor.org/rfc/rfc4647.html#section-3">RFC 4647 section 3<
```suggestion
        <dd>It performs "lookup" as defined in <a href="https://www.rfc-editor.org/rfc/bcp/bcp47.txt">BCP 47</a> at <a href="https://www.rfc-editor.org/rfc/rfc4647.html#section-3">RFC 4647 section 3</a>, determining the best element of _availableLocales_ for satisfying _requestedLocales_ using either the LookupMatchingLocaleByBestFit algorithm or LookupMatchingLocaleByPrefix algorithm as specified by _options_.[[localeMatcher]], ignoring Unicode locale extension sequences, and returns a representation of the match that also includes corresponding data from _localeData_ and a resolved value for each element of _relevantExtensionKeys_ (defaulting to data from the matched locale, superseded by data from the requested Unicode locale extension sequence if present and then by data from _options_ if present). If the matched element from _requestedLocales_ contains a Unicode locale extension sequence, it is copied onto the language tag in the [[Locale]] field of the returned Record, omitting any <code>keyword</code> Unicode locale nonterminal whose <code>key</code> value is not contained within _relevantExtensionKeys_ or <code>type</code> value is superseded by a different value from _options_.</dd>
```

2024-03-06 18:56 UTC, ben-allen commented on spec/negotiation.html
> +        <dd>It performs "lookup" as defined in <a href="https://www.rfc-editor.org/rfc/bcp/bcp47.txt">BCP 47</a> at <a href="https://www.rfc-editor.org/rfc/rfc4647.html#section-3">RFC 4647 section 3<
"and returns" rather than "and returning" appears to be the standard phrasing

2024-03-28 17:28 UTC, gibson042 commented
@ben-allen Accepted the suggestions with a few tweaks. I'm ready to land as soon as you approve.

2024-03-28 19:40 UTC, ben-allen approved these changes
LGTM!

2024-03-28 19:46 UTC, merged